### ISSUE TITLE
"readlink: illegal option -- f" in npm run prep-libs

### ISSUE THREAD

**Issue by scriptype** [mmikowski/hi_score#1] opened 2016-11-23 19:30 UTC
Hi, I was trying to see what's the deal with the project (sounds interesting indeed), so I did the following:

```
git clone git@github.com:mmikowski/hi_score.git
npm i
npm run prep-libs
```

I intentionally cloned it, instead of getting it through npm, as it felt a bit weird that way – `cd`ing into `node_modules/hi_score` and `npm install`ing there etc.

Seems like there's something wrong in prep-libs script. It stays hung after outputting this error:

```
npm run prep-libs                                                               
                                                                                          
> hi_score@0.6.23 prep-libs /Users/splash/workspace/hi_score                              
> bin/prep-libs.sh                                                                        
                                                                                          
prep-libs: start                                                                          
prep-libs: start layout_variables                                                         
readlink: illegal option -- f                                                             
usage: readlink [-n] [file ...] 
```

I have no idea about the problem there and I hope I'm doing everything correctly. Here's a recording of terminal on asciinema (Sorry it takes a bit long due to slow connection, error at 1:55):

[![asciicast](https://asciinema.org/a/ezg93wyuysymjdasdi4u109n7.png)](https://asciinema.org/a/ezg93wyuysymjdasdi4u109n7)

**Comment by mmikowski** [comment] 2016-11-23 20:06
Hi @scriptype 

I am almost certain you are using a Mac which uses the BSD tool chain instead of the GNU tool chain like Linux.  Bash on Ubuntu 16.10, for example, is version 4.3.46, not 3.2.  Version 3 was first released in 2004.  Bash 4 was released in 2009, and the scripts rely on version 4 associative array support.

The simplest solution is to run Ubuntu 16.10 Server in a Virtual Box. Everything should just work. Other options include  installing the GNU tools in Mac (and upgrading to Bash 4+), or use a Linux computer at your disposal (such as an AWS instance).  Generally, the Mac is always a PITA to get it to *almost* match a production system.

Now if you're one of those crazy folk who insist on getting Linux stuff to work on a Mac and want to provide a pull request, I'm open to that.  But at present I suggest we update the documentation and then close this issue.

**Comment by scriptype** [comment] 2016-11-23 21:43
Yes, I'm using a mac and yes seems like it's 3.x, although I'm not sure the toolchain part. I'm now trying to update it to 4.x via homebrew. 

```
bash --version
GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin15)
Copyright (C) 2007 Free Software Foundation, Inc.
```

**Comment by scriptype** [comment] 2016-11-23 22:26
Now I've updated bash to

```
bash --version
GNU bash, version 4.3.42(1)-release (x86_64-apple-darwin15.4.0)
```

and I've done some additional stuff to make it default bash like appending the path `/usr/local/bin/bash` to `/etc/shells`.

But the problem persists exactly as it was before:

[![asciicast](https://asciinema.org/a/1ygydzf35gmwzylx68guvanxp.png)](https://asciinema.org/a/1ygydzf35gmwzylx68guvanxp)

I've even changed the first line of prep-libs script to use the new bash's path, as the bash at the path it was pointing still is 3.x. This is the exact change I made (from git diff):

```
-#!/bin/bash
+#!/usr/local/bin/bash
```

I'm still unavailable to run the script. Running the whole thing in a VM-like environment isn't a viable option for me (I'm not that much familiar with this stuff). Wouldn't making the script more compatible be a more solid solution?

**Comment by mmikowski** [comment] 2016-11-23 22:29
You will want to swap out the BSD utilities for GNU utils too.  Here is the link:

https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/

Once you've confirmed that is complete and working, we can update the README.md to include the Mac-specific instructions.  I you want to offer a pull request, that would be welcome :)

**Comment by scriptype** [comment] 2016-11-24 00:04
I've installed coreutils and the first group of packages and ignored the last 2 groups of packages mentioned in that post, because I'm using some of them and don't want to touch their version or override them.

And, problem is still there.

**Comment by mmikowski** [comment] 2016-11-24 21:24
I would suggest you try running it on a Linux VM like an AWS instance running Ubuntu 16.10 server with developer tools installed first.  Once you see how its supposed to work, then you can port it over to Mac if you want.

I believe however the problem you are probably seeing, however, is that you setting the path to prefer the GNU tools so the BSD tools are still used by default.  readlink definitely supports an 'f' option in GNU tools, and probably has for decades.  Have you set the path per [this guide]( https://www.topbug.net/blog/2013/04/14/install-and-use-gnu-command-line-tools-in-mac-os-x/)?

`export PATH="$(brew --prefix coreutils)/libexec/gnubin:/usr/local/bin:$PATH"`

**Comment by mmikowski** [comment] 2016-11-28 02:18
@scriptype here is almost certainly a fix for your problem: http://stackoverflow.com/a/4031502

```bash
  $ brew install coreutils
  $ alias readlink="greadlink"
  $ readlink -f file.txt
```

I believe the coreutils package also provides a means to ensure the original file names are used.  One just needs to ensure that the path is first when using a Linux-like environment.

```bash
  $ export PATH="path/to/gnu/utils:$PATH"
  $ readlink -f file.txt
```

I have updated the README.md to include what we have learned so far (sorry, I don't own a Mac). Please let me know if that works for you and I will update the documentation further 

Cheers, Mike

**Comment by mmikowski** [comment] 2016-11-28 02:39
You may also try this.  Mac comes with a recent Perl installation, and Perl is required for SuperPack, so this may be a valid approach:

```bash
# Replace this in hi_score/bin/prep-libs.sh, line 19
LINK_PATH=$( readlink -f -- "${0}" ); 

# With this
readlinkf(){ perl -MCwd -e 'print Cwd::abs_path shift' "$1";}
LINK_PATH=$( readlinkf "${0}" );
```

**Comment by mmikowski** [comment] 2016-12-03 01:49
@scriptype please let me know if any of these suggestions resolve the issue so I may update the documentation and scripts and close this issue :)

**Comment by scriptype** [comment] 2016-12-05 22:52
I lost my interest and didn't try any of the given solutions.

**Comment by mmikowski** [comment] 2016-12-06 00:17
Documentation has been updated.  Closed for now.

**Closed by mmikowski** 2016-12-06 00:17 UTC

**Comment by stevenkasparwork** [comment] 2017-03-22 18:37
FYI I had the same issue on a MAC

```
> hi_score@1.1.1 setup /Users/stevenkaspar/Documents/Personal/Piano App/Code/hi_score
> bin/setup

start setup
  > layout vars
  > main
  >> main / verify env
  !! FAIL: Cannot write to /Users/stevenkaspar/Documents/Personal/Piano App/Code/node_modules/uglifyjs/lib/scope.js.
        Did you forget to run 'npm install' first?

npm ERR! Darwin 14.3.0
npm ERR! argv "/Users/stevenkaspar/.nvm/versions/node/v6.10.1/bin/node" "/Users/stevenkaspar/.nvm/versions/node/v6.10.1/bin/npm" "run" "setup"
npm ERR! node v6.10.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! hi_score@1.1.1 setup: `bin/setup`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the hi_score@1.1.1 setup script 'bin/setup'.
```

I am firing up Ubuntu 16.04 VirtualBox now though :)

**Comment by mmikowski** [comment] 2017-03-28 09:04
Thanks @stevenkasparwork.  I will update the docs once someone runs the gauntlet.  Notice that `prep-libs` is now replaced by `setup` in the latest release.

**Comment by mmikowski** [comment] 2017-04-06 08:59
This would be a serious issue if we were to deploy production code on Macs.  However nobody does that.

**Comment by mmikowski** [comment] 2017-09-12 00:09
@stevenkasparwork @scriptype FYI, hi_score 1.3 has been released and this issue should be resolved on Mac since most shell scripts have been replaced with the NodeJS `xhi` tool.
